--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/vijay/Pictures/Wallpapers/6.png"

-- Special
background="#020202"
foreground="#cbdfdf"
cursor="#cbdfdf"

-- Colors
color0="#020202"
color1="#77B9C4"
color2="#7FC0CA"
color3="#85B4B8"
color4="#94C7B7"
color5="#88BCC7"
color6="#94C6CD"
color7="#cbdfdf"
color8="#8e9c9c"
color9="#77B9C4"
color10="#7FC0CA"
color11="#85B4B8"
color12="#94C7B7"
color13="#88BCC7"
color14="#94C6CD"
color15="#cbdfdf"
